// Generated by CoffeeScript 1.7.1
(function() {
  var GH;

  GH = function(details) {
    var baseUrl, connectToAPI, errorHandler, events, org, repo, successHandler, user;
    baseUrl = "https://api.github.com/";
    successHandler = function(success) {
      return JSON.parse(success);
    };
    errorHandler = function() {
      throw new Error("Please provide either the user, repo's name and/or confirm events");
    };
    connectToAPI = function(req) {
      var xhrToGH;
      xhrToGH = new XMLHttpRequest();
      xhrToGH.open("get", req, false);
      xhrToGH.send();
      return xhrToGH.onload = (function() {
        return xhrToGH.response;
      })();
    };
    user = function() {
      var url;
      url = baseUrl + details.user;
      if (details.user) {
        return successHandler(connectToAPI(url));
      } else {
        return errorHandler;
      }
    };
    org = function() {
      var url;
      url = baseUrl + "orgs/" + details.organization;
      if (details.organization) {
        return successHandler(connectToAPI(url));
      } else {
        return errorHandler;
      }
    };
    repo = function() {
      var url;
      url = baseUrl + "repos/" + [details.user || details.organization, details.repo].join("/");
      if (details.repo && (details.user || details.orgranization)) {
        return successHandler(connectToAPI(url));
      } else {
        return errorHandler;
      }
    };
    events = function() {
      var url;
      url = baseUrl + "users/";
      url += [details.user || details.organization, "events"].join("/");
      if (details.events && details.organization || details.user) {
        return successHandler(connectToAPI(url));
      } else {
        return errorHandler;
      }
    };
    return {
      getUser: user,
      getOrganization: org,
      getRepo: repo,
      getEvents: events
    };
  };

}).call(this);
